// Runs as part of `registry:build` (see package.json), before `next dev`/`next build`.
// Scans public/thumbnails/ once and bakes the result into a plain data module so
// ComponentCardMedia (a client component, rendered ~200+ times on /components and
// /elements) can skip mounting an <img>/<video> for a slug that has no thumbnail
// file yet, instead of firing the request and waiting for it to 404. Without this,
// every card with no thumbnail sends two doomed requests (.webp + .mp4), and with
// well over 100 such slugs at once, that request storm is what was dragging the
// catalog pages' load event out past two seconds.
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const thumbDir = path.join(process.cwd(), "public", "thumbnails");

let files: string[] = [];
try {
  files = readdirSync(thumbDir);
} catch {
  files = [];
}

const images = new Set<string>();
const videos = new Set<string>();
for (const file of files) {
  if (file.endsWith(".webp")) images.add(file.slice(0, -".webp".length));
  else if (file.endsWith(".mp4")) videos.add(file.slice(0, -".mp4".length));
}

const out = `// Auto-generated by scripts/generate-thumbnail-manifest.mts on every
// \`registry:build\` run — do not edit by hand, it will be overwritten.
export const THUMBNAIL_IMAGE_SLUGS: readonly string[] = ${JSON.stringify([...images].sort())};
export const THUMBNAIL_VIDEO_SLUGS: readonly string[] = ${JSON.stringify([...videos].sort())};
`;

const outPath = path.join(process.cwd(), "src", "lib", "thumbnail-manifest.ts");
writeFileSync(outPath, out);
console.log(`thumbnail-manifest.ts: ${images.size} images, ${videos.size} videos`);
